"""Compare two quarterbacks using the current GridironIQ weekly output.

Usage:
    py compare_qbs.py "Dak Prescott" "Bryce Young"

The script reads the latest weekly rankings generated by run_weekly.py and
prints a side-by-side start/sit comparison using the official GridironIQ v2
projection plus descriptive matchup context.
"""

from __future__ import annotations

from difflib import get_close_matches
from pathlib import Path
import argparse

import pandas as pd

ROOT = Path(__file__).resolve().parent
RANKINGS_FILE = ROOT / "data" / "processed" / "qb_v2_weekly_rankings.csv"
ALL_FUTURE_FILE = (
    ROOT / "data" / "processed" / "qb_v2_all_future_candidates.csv"
)


def safe_float(value) -> float | None:
    try:
        if pd.isna(value):
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def fmt(value: float | None, digits: int = 1, suffix: str = "") -> str:
    if value is None:
        return "N/A"
    return f"{value:.{digits}f}{suffix}"


def load_current_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    if not RANKINGS_FILE.exists():
        raise FileNotFoundError(
            "Missing qb_v2_weekly_rankings.csv. Run 'py run_weekly.py' first."
        )

    rankings = pd.read_csv(RANKINGS_FILE, low_memory=False)

    if ALL_FUTURE_FILE.exists():
        future = pd.read_csv(ALL_FUTURE_FILE, low_memory=False)
    else:
        future = rankings.copy()

    return rankings, future


def find_player(
    query: str,
    rankings: pd.DataFrame,
    future: pd.DataFrame,
) -> pd.Series:
    query_clean = query.strip().lower()

    if not query_clean:
        raise ValueError("Player name cannot be empty.")

    # Prefer official weekly ranking rows.
    names = rankings["player_name"].astype(str)
    exact = rankings[names.str.lower().eq(query_clean)]
    if len(exact) == 1:
        return exact.iloc[0]

    partial = rankings[names.str.lower().str.contains(query_clean, regex=False)]
    if len(partial) == 1:
        return partial.iloc[0]

    # Fall back to all future candidates so a user can still compare a backup
    # or a player the production gate did not select.
    future_names = future["player_name"].astype(str)
    exact_future = future[future_names.str.lower().eq(query_clean)]
    if len(exact_future) == 1:
        return exact_future.iloc[0]

    partial_future = future[
        future_names.str.lower().str.contains(query_clean, regex=False)
    ]
    if len(partial_future) == 1:
        return partial_future.iloc[0]

    unique_names = sorted(
        set(names.dropna().tolist()) | set(future_names.dropna().tolist())
    )
    match = get_close_matches(query, unique_names, n=1, cutoff=0.55)

    if match:
        matched = future[future_names.eq(match[0])]
        if len(matched):
            print(f"Using closest match for '{query}': {match[0]}")
            return matched.iloc[0]

    raise ValueError(
        f"Could not find a current-week QB matching '{query}'. "
        "Run 'py run_weekly.py' to refresh the weekly rankings."
    )


def current_rank(row: pd.Series, rankings: pd.DataFrame) -> str:
    player_id = str(row.get("player_id", ""))
    match = rankings[
        rankings["player_id"].astype(str).eq(player_id)
    ]

    if len(match):
        rank = safe_float(match.iloc[0].get("rank"))
        return f"QB{int(rank)}" if rank is not None else "Ranked"

    return "Not selected"


def projection(row: pd.Series) -> float:
    value = safe_float(row.get("gridironiq_projection"))
    return value if value is not None else 0.0


def role_probability(row: pd.Series) -> float | None:
    return safe_float(row.get("meaningful_role_probability"))


def prediction_interval(row: pd.Series) -> tuple[float | None, float | None]:
    return (
        safe_float(row.get("prediction_low_80")),
        safe_float(row.get("prediction_high_80")),
    )


def comparison_value(
    row: pd.Series,
    column: str,
) -> float | None:
    return safe_float(row.get(column))


def choose_higher(
    a: pd.Series,
    b: pd.Series,
    column: str,
    tolerance: float = 0.0,
) -> str:
    av = comparison_value(a, column)
    bv = comparison_value(b, column)

    if av is None or bv is None:
        return "N/A"

    if abs(av - bv) <= tolerance:
        return "Similar"

    return str(a["player_name"]) if av > bv else str(b["player_name"])


def choose_lower(
    a: pd.Series,
    b: pd.Series,
    column: str,
    tolerance: float = 0.0,
) -> str:
    av = comparison_value(a, column)
    bv = comparison_value(b, column)

    if av is None or bv is None:
        return "N/A"

    if abs(av - bv) <= tolerance:
        return "Similar"

    return str(a["player_name"]) if av < bv else str(b["player_name"])


def recommendation_label(gap: float) -> str:
    gap = abs(gap)
    if gap < 1.0:
        return "Essentially a toss-up"
    if gap < 3.0:
        return "Slight lean"
    if gap < 6.0:
        return "Clear lean"
    return "Strong lean"


def print_player_summary(
    row: pd.Series,
    rankings: pd.DataFrame,
) -> None:
    proj = projection(row)
    role = role_probability(row)
    rank = current_rank(row, rankings)

    print(f"{row['player_name']} ({row['team']} vs {row['opponent']})")
    print(f"  Rank:       {rank}")
    print(f"  Projection: {proj:.2f} FP")
    low, high = prediction_interval(row)
    if low is not None and high is not None:
        print(f"  80% range:  {low:.2f} to {high:.2f} FP")
    print(
        "  Role:       "
        + (f"{role:.1%}" if role is not None else "N/A")
    )
    print(f"  Location:   {str(row.get('home_away', 'N/A')).title()}")
    print(
        "  Positives:  "
        + str(row.get("key_positives", "No explanation available"))
    )
    print(
        "  Negatives:  "
        + str(row.get("key_negatives", "No explanation available"))
    )


def print_model_attribution(row: pd.Series) -> None:
    """Print exact SHAP attribution for the conditional points model."""
    from src.models.explain_qb_v2 import explain_conditional_prediction

    try:
        result = explain_conditional_prediction(
            player_id=str(row["player_id"]),
            season=int(safe_float(row.get("season")) or 0),
            week=int(safe_float(row.get("week")) or 0),
            team=str(row["team"]),
            top_n=4,
        )
    except RuntimeError as exc:
        print(f"  SHAP unavailable: {exc}")
        return

    print(
        f"  Conditional-model baseline: "
        f"{result['baseline']:.2f} FP"
    )
    print(
        f"  Conditional-model output:   "
        f"{result['pipeline_prediction']:.2f} FP"
    )

    print("  Model factors pushing UP:")
    for item in result["positive"]:
        print(
            f"    + {item['label']:<34} "
            f"{item['contribution']:+.2f} FP "
            f"(value={item['value']})"
        )

    if not result["positive"]:
        print("    + No positive SHAP contributions")

    print("  Model factors pushing DOWN:")
    for item in result["negative"]:
        print(
            f"    - {item['label']:<34} "
            f"{item['contribution']:+.2f} FP "
            f"(value={item['value']})"
        )

    if not result["negative"]:
        print("    - No negative SHAP contributions")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare two QBs using current GridironIQ projections."
    )
    parser.add_argument("qb1", help='First QB, e.g. "Dak Prescott"')
    parser.add_argument("qb2", help='Second QB, e.g. "Bryce Young"')
    args = parser.parse_args()

    rankings, future = load_current_data()

    a = find_player(args.qb1, rankings, future)
    b = find_player(args.qb2, rankings, future)

    season = int(safe_float(rankings.iloc[0].get("season")) or 0)
    week = int(safe_float(rankings.iloc[0].get("week")) or 0)

    print("GRIDIRONIQ QB START / SIT COMPARISON")
    print("=" * 76)
    print(f"Season {season} | Week {week}\n")

    print_player_summary(a, rankings)
    print()
    print_player_summary(b, rankings)

    a_proj = projection(a)
    b_proj = projection(b)
    diff = a_proj - b_proj

    print("\n" + "=" * 76)
    print("SIDE-BY-SIDE SIGNALS")
    print("=" * 76)

    categories = [
        (
            "Recent fantasy form",
            choose_higher(a, b, "avg_fp_last_3", tolerance=1.0),
            fmt(comparison_value(a, "avg_fp_last_3"), 1, " FP"),
            fmt(comparison_value(b, "avg_fp_last_3"), 1, " FP"),
        ),
        (
            "Passing matchup",
            choose_higher(
                a,
                b,
                "opp_avg_pass_yards_allowed_last_3",
                tolerance=10.0,
            ),
            fmt(
                comparison_value(
                    a,
                    "opp_avg_pass_yards_allowed_last_3",
                ),
                0,
                " yds",
            ),
            fmt(
                comparison_value(
                    b,
                    "opp_avg_pass_yards_allowed_last_3",
                ),
                0,
                " yds",
            ),
        ),
        (
            "Pass-rush matchup",
            choose_lower(
                a,
                b,
                "opp_avg_def_sacks_last_3",
                tolerance=0.3,
            ),
            fmt(
                comparison_value(a, "opp_avg_def_sacks_last_3"),
                1,
                " sacks",
            ),
            fmt(
                comparison_value(b, "opp_avg_def_sacks_last_3"),
                1,
                " sacks",
            ),
        ),
        (
            "Game environment",
            choose_higher(a, b, "game_total_line", tolerance=1.0),
            fmt(comparison_value(a, "game_total_line"), 1),
            fmt(comparison_value(b, "game_total_line"), 1),
        ),
        (
            "Role confidence",
            choose_higher(
                a,
                b,
                "meaningful_role_probability",
                tolerance=0.03,
            ),
            (
                f"{role_probability(a):.1%}"
                if role_probability(a) is not None
                else "N/A"
            ),
            (
                f"{role_probability(b):.1%}"
                if role_probability(b) is not None
                else "N/A"
            ),
        ),
    ]

    print(
        f"{'Category':<23}"
        f"{str(a['player_name']):>16}"
        f"{str(b['player_name']):>16}"
        f"{'Edge':>18}"
    )
    print("-" * 76)

    for label, edge, avalue, bvalue in categories:
        print(
            f"{label:<23}"
            f"{avalue:>16}"
            f"{bvalue:>16}"
            f"{edge:>18}"
        )

    print("\n" + "=" * 76)
    print("MODEL ATTRIBUTION (SHAP)")
    print("=" * 76)
    print(
        "These values explain the Random Forest's conditional fantasy-points "
        "prediction in fantasy-point units. They do not explain the separate "
        "role classifier or team-selection gate."
    )

    print(f"\n{a['player_name']}")
    print_model_attribution(a)

    print(f"\n{b['player_name']}")
    print_model_attribution(b)

    print("\n" + "=" * 76)
    print("GRIDIRONIQ LEAN")
    print("=" * 76)

    if diff >= 0:
        preferred = a
        other = b
    else:
        preferred = b
        other = a

    gap = abs(diff)
    label = recommendation_label(gap)

    print(
        f"{label}: START {preferred['player_name']} over "
        f"{other['player_name']}."
    )
    print(
        f"Projection gap: {gap:.2f} FP "
        f"({projection(preferred):.2f} vs {projection(other):.2f})."
    )

    preferred_low, preferred_high = prediction_interval(preferred)
    other_low, other_high = prediction_interval(other)
    if (
        preferred_low is not None
        and preferred_high is not None
        and other_low is not None
        and other_high is not None
    ):
        overlap = max(
            0.0,
            min(preferred_high, other_high)
            - max(preferred_low, other_low),
        )
        if overlap > 0:
            print(
                "Uncertainty note: the historical 80% prediction ranges "
                f"overlap by {overlap:.2f} FP, so the point-estimate edge "
                "is not a guarantee."
            )

    preferred_role = role_probability(preferred)
    if preferred_role is not None and preferred_role < 0.75:
        print(
            "Caution: the preferred QB has below-75% meaningful-role "
            "confidence, so check late injury/starter news."
        )

    print(
        "\nContext notes are descriptive signals. The SHAP section is the "
        "exact additive attribution for the conditional Random Forest output; "
        "the role classifier and team-selection gate are separate. The 80% "
        "range is calibrated from historical 2023-2025 walk-forward residuals "
        "and is not a guaranteed bound."
    )


if __name__ == "__main__":
    main()
