"""Optimize a roster using official GridironIQ weekly projections.

Supported lineup positions:
    QB, RB, WR, TE, K
FLEX eligibility for this league:
    RB or WR only

D/ST is intentionally unsupported for now and does not participate in
the optimizer.

Roster CSV:
    player_name,position,player_id

Only player_name is required. position and player_id are optional but
recommended when names could be ambiguous. The optimizer uses the
official current-week ranking files generated by run_weekly.py.

Default slot counts are convenience defaults, NOT inferred league rules:
    1 QB, 2 RB, 2 WR, 1 TE, 1 RB/WR FLEX, 1 K

Example:
    py src\lineup\optimize_lineup.py --roster data\roster.csv
    py src\lineup\optimize_lineup.py --roster data\roster.csv --rb 2 --wr 3 --flex 1

The output includes one-for-one bench alternatives and individual 80%
historical prediction ranges. Individual player intervals are not summed
into a claimed lineup-level 80% interval.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"

POSITION_FILES = {
    "QB": PROCESSED / "qb_v2_weekly_rankings.csv",
    "RB": PROCESSED / "rb_v2_weekly_rankings.csv",
    "WR": PROCESSED / "wr_v2_weekly_rankings.csv",
    "TE": PROCESSED / "te_v2_weekly_rankings.csv",
    "K": PROCESSED / "k_v2_weekly_rankings.csv",
}
SUPPORTED_POSITIONS = tuple(POSITION_FILES)
UNSUPPORTED_DEFENSE_CODES = {"DST", "D/ST", "DEF", "DEFENSE"}

LINEUP_FILE = PROCESSED / "optimal_lineup.csv"
BENCH_FILE = PROCESSED / "lineup_bench.csv"
UNAVAILABLE_FILE = PROCESSED / "lineup_unavailable.csv"

POOL_COLUMNS = [
    "player_id", "player_name", "position",
    "season", "week", "team", "opponent",
    "gridironiq_projection",
    "prediction_low_80", "prediction_high_80",
    "key_positives", "key_negatives",
]


@dataclass(frozen=True)
class Slot:
    label: str
    eligible_positions: tuple[str, ...]


def normalize_name(value: object) -> str:
    return str(value).strip().casefold()


def normalize_position(value: object) -> str:
    return str(value).strip().upper()


def load_projection_pool() -> pd.DataFrame:
    """Load the official ranking for every supported position."""
    frames: list[pd.DataFrame] = []
    weeks: set[tuple[int, int]] = set()

    for position, path in POSITION_FILES.items():
        if not path.is_file():
            raise FileNotFoundError(
                f"Missing {path}. Run py run_weekly.py first."
            )
        frame = pd.read_csv(
            path,
            low_memory=False,
            dtype={"player_id": str},
        )
        if frame.empty:
            raise RuntimeError(
                f"{position} weekly rankings are empty: {path}"
            )
        required = [
            "player_id", "player_name",
            "season", "week", "team", "opponent",
            "gridironiq_projection",
        ]
        missing = [
            column for column in required
            if column not in frame.columns
        ]
        if missing:
            raise RuntimeError(
                f"{position} rankings missing fields: {missing}"
            )

        frame["season"] = pd.to_numeric(
            frame["season"], errors="raise"
        ).astype(int)
        frame["week"] = pd.to_numeric(
            frame["week"], errors="raise"
        ).astype(int)
        unique_weeks = frame[
            ["season", "week"]
        ].drop_duplicates()
        if len(unique_weeks) != 1:
            raise RuntimeError(
                f"{position} rankings contain multiple season/weeks."
            )
        weeks.add(tuple(
            int(value)
            for value in unique_weeks.iloc[0].tolist()
        ))

        frame["position"] = position
        frame["gridironiq_projection"] = pd.to_numeric(
            frame["gridironiq_projection"],
            errors="raise",
        )
        for column in [
            "prediction_low_80",
            "prediction_high_80",
        ]:
            if column not in frame:
                frame[column] = pd.NA
            frame[column] = pd.to_numeric(
                frame[column], errors="coerce"
            )
        for column in ["key_positives", "key_negatives"]:
            if column not in frame:
                frame[column] = pd.NA

        frames.append(frame[POOL_COLUMNS].copy())

    if len(weeks) != 1:
        raise RuntimeError(
            "Official position rankings disagree on season/week: "
            f"{sorted(weeks)}. Run the weekly pipeline again."
        )

    pool = pd.concat(frames, ignore_index=True)
    pool["player_id"] = pool["player_id"].astype(str).str.strip()
    pool["player_name_key"] = pool["player_name"].map(
        normalize_name
    )
    if pool.duplicated(
        ["position", "player_id", "season", "week"]
    ).any():
        raise RuntimeError(
            "Duplicate official player projections detected."
        )
    return pool


def load_roster(
    path: Path,
    pool: pd.DataFrame,
    *,
    strict_unmatched: bool = False,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Resolve roster rows against official current-week projections."""
    if not path.is_file():
        raise FileNotFoundError(path)

    roster = pd.read_csv(
        path,
        low_memory=False,
        dtype={"player_id": str},
    )
    if "player_name" not in roster.columns:
        raise RuntimeError(
            "Roster CSV must contain a player_name column."
        )
    if roster.empty:
        raise RuntimeError("Roster CSV is empty.")

    if "position" not in roster:
        roster["position"] = pd.NA
    if "player_id" not in roster:
        roster["player_id"] = pd.NA

    matched_rows: list[dict] = []
    unavailable_rows: list[dict] = []

    for row_number, row in roster.iterrows():
        supplied_name = str(row["player_name"]).strip()
        supplied_position = (
            normalize_position(row["position"])
            if pd.notna(row["position"])
            and str(row["position"]).strip()
            else ""
        )
        supplied_id = (
            str(row["player_id"]).strip()
            if pd.notna(row["player_id"])
            and str(row["player_id"]).strip()
            and str(row["player_id"]).lower() != "nan"
            else ""
        )

        if supplied_position in UNSUPPORTED_DEFENSE_CODES:
            unavailable_rows.append({
                "roster_row": row_number + 2,
                "player_name": supplied_name,
                "position": supplied_position,
                "player_id": supplied_id or pd.NA,
                "reason": "D/ST intentionally unsupported",
            })
            continue

        candidates = pool.copy()
        if supplied_id:
            candidates = candidates[
                candidates["player_id"].eq(supplied_id)
            ]
        else:
            candidates = candidates[
                candidates["player_name_key"].eq(
                    normalize_name(supplied_name)
                )
            ]

        if supplied_position:
            if supplied_position not in SUPPORTED_POSITIONS:
                unavailable_rows.append({
                    "roster_row": row_number + 2,
                    "player_name": supplied_name,
                    "position": supplied_position,
                    "player_id": supplied_id or pd.NA,
                    "reason": "unsupported position",
                })
                continue
            candidates = candidates[
                candidates["position"].eq(supplied_position)
            ]

        if len(candidates) == 0:
            unavailable_rows.append({
                "roster_row": row_number + 2,
                "player_name": supplied_name,
                "position": supplied_position or pd.NA,
                "player_id": supplied_id or pd.NA,
                "reason": (
                    "not in current pregame ranking pool "
                    "(bye/locked game/name or ID mismatch)"
                ),
            })
            continue

        if len(candidates) > 1:
            options = candidates[
                ["player_id", "player_name", "position"]
            ].to_dict("records")
            raise ValueError(
                f"Roster row {row_number + 2} is ambiguous: "
                f"{supplied_name!r}. Use player_id. "
                f"Matches={options}"
            )

        official = candidates.iloc[0].to_dict()
        official["roster_row"] = row_number + 2
        matched_rows.append(official)

    matched = pd.DataFrame(matched_rows)
    unavailable = pd.DataFrame(unavailable_rows)

    if not matched.empty and matched["player_id"].duplicated().any():
        duplicate_ids = (
            matched.loc[
                matched["player_id"].duplicated(keep=False),
                ["player_id", "player_name"],
            ]
            .drop_duplicates()
            .to_dict("records")
        )
        raise ValueError(
            f"Roster contains duplicate matched players: {duplicate_ids}"
        )

    if strict_unmatched and not unavailable.empty:
        raise ValueError(
            "Roster contains unavailable/unmatched rows: "
            + str(unavailable.to_dict("records"))
        )

    return matched, unavailable


def build_slots(
    *,
    qb: int,
    rb: int,
    wr: int,
    te: int,
    flex: int,
    k: int,
) -> list[Slot]:
    counts = {
        "qb": qb, "rb": rb, "wr": wr,
        "te": te, "flex": flex, "k": k,
    }
    if any(value < 0 for value in counts.values()):
        raise ValueError("Lineup slot counts cannot be negative.")

    slots: list[Slot] = []
    definitions = [
        ("QB", qb, ("QB",)),
        ("RB", rb, ("RB",)),
        ("WR", wr, ("WR",)),
        ("TE", te, ("TE",)),
        ("FLEX", flex, ("RB", "WR")),
        ("K", k, ("K",)),
    ]
    for base, count, eligible in definitions:
        for index in range(1, count + 1):
            label = base if count == 1 else f"{base}{index}"
            slots.append(Slot(label, eligible))
    if not slots:
        raise ValueError("At least one lineup slot is required.")
    return slots


def _eligible(
    roster: pd.DataFrame,
    slot: Slot,
) -> pd.DataFrame:
    return roster[
        roster["position"].isin(slot.eligible_positions)
    ].copy()


def optimize(
    roster: pd.DataFrame,
    slots: list[Slot],
) -> dict[str, pd.Series]:
    """Exact lineup optimization by branch-and-bound over a small roster."""
    if roster.empty:
        raise RuntimeError("No matched roster players to optimize.")

    candidates = {
        slot.label: _eligible(roster, slot)
        .sort_values(
            ["gridironiq_projection", "player_id"],
            ascending=[False, True],
        )
        for slot in slots
    }
    missing_slots = [
        slot.label
        for slot in slots
        if candidates[slot.label].empty
    ]
    if missing_slots:
        raise RuntimeError(
            "Roster cannot fill required lineup slots: "
            + ", ".join(missing_slots)
        )

    # Search constrained positions first to reduce branching.
    slot_lookup = {slot.label: slot for slot in slots}
    search_order = sorted(
        slots,
        key=lambda slot: (
            len(candidates[slot.label]),
            len(slot.eligible_positions),
            slot.label,
        ),
    )

    # Upper bound for remaining slots ignores player uniqueness,
    # making it optimistic and therefore safe for pruning.
    max_by_slot = {
        slot.label: float(
            candidates[slot.label][
                "gridironiq_projection"
            ].max()
        )
        for slot in slots
    }

    best_score = float("-inf")
    best_key: tuple[str, ...] | None = None
    best_assignment: dict[str, pd.Series] | None = None

    def search(
        index: int,
        used: set[str],
        score: float,
        assignment: dict[str, pd.Series],
    ) -> None:
        nonlocal best_score, best_key, best_assignment

        if index == len(search_order):
            # Deterministic tiebreak by original lineup slot order.
            key = tuple(
                str(assignment[slot.label]["player_id"])
                for slot in slots
            )
            if (
                score > best_score + 1e-12
                or (
                    abs(score - best_score) <= 1e-12
                    and (best_key is None or key < best_key)
                )
            ):
                best_score = score
                best_key = key
                best_assignment = dict(assignment)
            return

        remaining = search_order[index:]
        optimistic = score + sum(
            max_by_slot[slot.label]
            for slot in remaining
        )
        if optimistic < best_score - 1e-12:
            return

        slot = search_order[index]
        for _, player in candidates[slot.label].iterrows():
            player_id = str(player["player_id"])
            if player_id in used:
                continue
            used.add(player_id)
            assignment[slot.label] = player
            search(
                index + 1,
                used,
                score + float(
                    player["gridironiq_projection"]
                ),
                assignment,
            )
            del assignment[slot.label]
            used.remove(player_id)

    search(0, set(), 0.0, {})

    if best_assignment is None:
        requirements = ", ".join(
            f"{slot.label}:{'/'.join(slot.eligible_positions)}"
            for slot in slots
        )
        raise RuntimeError(
            "No legal lineup can be built from the matched roster. "
            f"Required slots: {requirements}"
        )

    # Return in user-facing slot order.
    return {
        slot.label: best_assignment[slot.label]
        for slot in slots
    }


def _intervals_overlap(
    first: pd.Series,
    second: pd.Series,
) -> object:
    values = [
        first.get("prediction_low_80"),
        first.get("prediction_high_80"),
        second.get("prediction_low_80"),
        second.get("prediction_high_80"),
    ]
    if any(pd.isna(value) for value in values):
        return pd.NA
    return bool(
        float(first["prediction_low_80"])
        <= float(second["prediction_high_80"])
        and float(second["prediction_low_80"])
        <= float(first["prediction_high_80"])
    )


def build_outputs(
    roster: pd.DataFrame,
    slots: list[Slot],
    assignment: dict[str, pd.Series],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    starter_ids = {
        str(player["player_id"])
        for player in assignment.values()
    }
    bench = roster[
        ~roster["player_id"].astype(str).isin(starter_ids)
    ].copy().sort_values(
        ["gridironiq_projection", "position", "player_name"],
        ascending=[False, True, True],
    )

    rows = []
    for slot in slots:
        player = assignment[slot.label]
        eligible_bench = bench[
            bench["position"].isin(slot.eligible_positions)
        ].sort_values(
            ["gridironiq_projection", "player_id"],
            ascending=[False, True],
        )
        alternative = (
            eligible_bench.iloc[0]
            if not eligible_bench.empty
            else None
        )
        projection = float(
            player["gridironiq_projection"]
        )
        alt_projection = (
            float(alternative["gridironiq_projection"])
            if alternative is not None
            else pd.NA
        )
        rows.append({
            "slot": slot.label,
            "position": player["position"],
            "player_id": player["player_id"],
            "player_name": player["player_name"],
            "team": player["team"],
            "opponent": player["opponent"],
            "gridironiq_projection": projection,
            "prediction_low_80": player[
                "prediction_low_80"
            ],
            "prediction_high_80": player[
                "prediction_high_80"
            ],
            "best_bench_alternative": (
                alternative["player_name"]
                if alternative is not None
                else pd.NA
            ),
            "alternative_position": (
                alternative["position"]
                if alternative is not None
                else pd.NA
            ),
            "alternative_projection": alt_projection,
            "projection_margin": (
                projection - float(alt_projection)
                if pd.notna(alt_projection)
                else pd.NA
            ),
            "individual_80_ranges_overlap": (
                _intervals_overlap(player, alternative)
                if alternative is not None
                else pd.NA
            ),
            "key_positives": player.get(
                "key_positives", pd.NA
            ),
            "key_negatives": player.get(
                "key_negatives", pd.NA
            ),
        })

    lineup = pd.DataFrame(rows)
    bench_columns = [
        "position", "player_id", "player_name",
        "team", "opponent", "gridironiq_projection",
        "prediction_low_80", "prediction_high_80",
        "key_positives", "key_negatives",
    ]
    return lineup, bench[bench_columns].reset_index(drop=True)


def _print_lineup(
    lineup: pd.DataFrame,
    bench: pd.DataFrame,
    unavailable: pd.DataFrame,
) -> None:
    first = lineup.iloc[0]
    total = lineup["gridironiq_projection"].sum()

    print("GRIDIRONIQ OPTIMAL STARTING LINEUP")
    print("=" * 112)
    print(
        f"Season {int(first['season']) if 'season' in first else '?'}"
        if False else
        f"Projected starter total: {total:.2f} FP"
    )
    display = lineup[
        [
            "slot", "position", "player_name",
            "team", "opponent",
            "gridironiq_projection",
            "prediction_low_80",
            "prediction_high_80",
            "best_bench_alternative",
            "alternative_projection",
            "projection_margin",
            "individual_80_ranges_overlap",
        ]
    ]
    print(
        display.to_string(
            index=False,
            formatters={
                "gridironiq_projection": "{:.2f}".format,
                "prediction_low_80": (
                    lambda value:
                    "" if pd.isna(value)
                    else f"{float(value):.2f}"
                ),
                "prediction_high_80": (
                    lambda value:
                    "" if pd.isna(value)
                    else f"{float(value):.2f}"
                ),
                "alternative_projection": (
                    lambda value:
                    "" if pd.isna(value)
                    else f"{float(value):.2f}"
                ),
                "projection_margin": (
                    lambda value:
                    "" if pd.isna(value)
                    else f"{float(value):+.2f}"
                ),
            },
        )
    )
    print(
        "\n80% ranges shown above are individual historical player "
        "intervals; they are not a calibrated lineup-total interval."
    )

    print("\nBENCH")
    print("=" * 112)
    if bench.empty:
        print("No matched bench players.")
    else:
        print(
            bench[
                [
                    "position", "player_name",
                    "team", "opponent",
                    "gridironiq_projection",
                    "prediction_low_80",
                    "prediction_high_80",
                ]
            ].to_string(
                index=False,
                formatters={
                    "gridironiq_projection": "{:.2f}".format,
                    "prediction_low_80": (
                        lambda value:
                        "" if pd.isna(value)
                        else f"{float(value):.2f}"
                    ),
                    "prediction_high_80": (
                        lambda value:
                        "" if pd.isna(value)
                        else f"{float(value):.2f}"
                    ),
                },
            )
        )

    if not unavailable.empty:
        print("\nUNAVAILABLE / UNSUPPORTED ROSTER ROWS")
        print("=" * 112)
        print(unavailable.to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Optimize a roster using official GridironIQ "
            "QB/RB/WR/TE/K projections and RB/WR-only FLEX."
        )
    )
    parser.add_argument(
        "--roster",
        type=Path,
        required=True,
        help=(
            "CSV with player_name and optional position/player_id."
        ),
    )
    parser.add_argument(
        "--qb", type=int, default=1,
        help="Starting QB slots (default: 1).",
    )
    parser.add_argument(
        "--rb", type=int, default=2,
        help="Starting RB slots (default: 2).",
    )
    parser.add_argument(
        "--wr", type=int, default=2,
        help="Starting WR slots (default: 2).",
    )
    parser.add_argument(
        "--te", type=int, default=1,
        help="Starting TE slots (default: 1).",
    )
    parser.add_argument(
        "--flex", type=int, default=1,
        help="RB/WR-only FLEX slots (default: 1).",
    )
    parser.add_argument(
        "--k", type=int, default=1,
        help="Starting Kicker slots (default: 1).",
    )
    parser.add_argument(
        "--strict-unmatched",
        action="store_true",
        help=(
            "Fail if any roster row is unavailable/unsupported "
            "instead of reporting and excluding it."
        ),
    )
    args = parser.parse_args()

    pool = load_projection_pool()
    roster, unavailable = load_roster(
        args.roster,
        pool,
        strict_unmatched=args.strict_unmatched,
    )
    slots = build_slots(
        qb=args.qb,
        rb=args.rb,
        wr=args.wr,
        te=args.te,
        flex=args.flex,
        k=args.k,
    )
    assignment = optimize(roster, slots)
    lineup, bench = build_outputs(
        roster, slots, assignment
    )

    # Season/week are common to all official inputs.
    first = pool.iloc[0]
    lineup.insert(0, "week", int(first["week"]))
    lineup.insert(0, "season", int(first["season"]))
    bench.insert(0, "week", int(first["week"]))
    bench.insert(0, "season", int(first["season"]))

    LINEUP_FILE.parent.mkdir(
        parents=True, exist_ok=True
    )
    lineup.to_csv(LINEUP_FILE, index=False)
    bench.to_csv(BENCH_FILE, index=False)
    unavailable.to_csv(UNAVAILABLE_FILE, index=False)

    _print_lineup(lineup, bench, unavailable)
    print(f"\nSaved optimal lineup: {LINEUP_FILE}")
    print(f"Saved bench:          {BENCH_FILE}")
    print(f"Saved unavailable:    {UNAVAILABLE_FILE}")


if __name__ == "__main__":
    main()
